apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  annotations:
    ansible.sdk.operatorframework.io/verbosity: "1"
    meta.helm.sh/release-name: kiali-operator
    meta.helm.sh/release-namespace: kiali-operator
  creationTimestamp: "2022-08-25T19:06:43Z"
  finalizers:
  - kiali.io/finalizer
  generation: 3
  labels:
    app: kiali-operator
    app.kubernetes.io/instance: kiali-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kiali-operator
    app.kubernetes.io/part-of: kiali-operator
    app.kubernetes.io/version: v1.55.0
    helm.sh/chart: kiali-operator-1.55.0
    version: v1.55.0
  name: kiali
  namespace: istio-system
spec:
  deployment:
    accessible_namespaces:
    - '**'
  auth:
    strategy: anonymous    
status:
  conditions:
  - ansibleResult:
      changed: 10
      completion: 2022-08-25T19:53:23.851336
      failures: 0
      ok: 104
      skipped: 96
    lastTransitionTime: "2022-08-25T19:07:03Z"
    message: Awaiting next reconciliation
    reason: Successful
    status: "True"
    type: Running
  deployment:
    accessibleNamespaces: '**'
    instanceName: kiali
    namespace: istio-system
  environment:
    isKubernetes: true
    kubernetesVersion: 1.23.8
    operatorVersion: v1.55.0
  progress:
    duration: "0:00:31"
    message: 6. Finished all resource creation
  specVersion: default
